steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "asia.gcr.io/miloo-phoenix/heimdall:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/miloo-phoenix/heimdall:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gke-deploy:stable"
    args:
    - run
    - --filename=deployment.yaml
    - --image=asia.gcr.io/miloo-phoenix/heimdall:$SHORT_SHA
    - --location=asia-southeast1
    - --cluster=main