apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall-service
  template:
    metadata:
      labels:
        app: heimdall-service
    spec:
      containers:
        - name: heimdall-service
          image: asia.gcr.io/miloo-phoenix/heimdall
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: heimdall-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: heimdall-service
  ports:
    - port: 8000
      targetPort: 8080
